<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>SpeechTool</RootNamespace>
    <AssemblyName>SpeechTool</AssemblyName>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.21.0" />
    <PackageReference Include="Microsoft.CognitiveServices.Speech" Version="1.51.1" />
    <PackageReference Include="System.CommandLine" Version="2.0.10" />
  </ItemGroup>
</Project>
